services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports: ["8080:8080"]

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports: ["80:80"]
